services:
  - name: card-trading-app
    type: web
    env: node
    plan: free
    region: frankfurt
    buildCommand: |
      cd backend
      yarn
      yarn build
    startCommand: yarn start-js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
