services:
  - name: card-trading-app
    type: web
    env: node
    plan: free
    region: frankfurt
    buildCommand: |
      cd backend
      yarn
      yarn build
      ls -R dist
      ls -R .
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
