services:
  - name: card-trading-app
    type: web
    env: node
    plan: free
    region: frankfurt
    buildCommand: |
      cd backend
      yarn
      yarn build
      ls -l dist
    startCommand: node backend/dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
