name: Integración Continua

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/-1', 'lts/*', 'current']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Install Dependencies
      run: cd backend && yarn install

    - name: Build Docker Images
      run: docker-compose build

    - name: Start Docker Containers
      run: docker-compose up -d

    - name: Wait for Services
      run: |
        echo "Esperando que PostgreSQL y otros servicios se inicien..."
        sleep 15
        until docker exec db pg_isready -U pokemon_admin; do
          echo "Esperando a PostgreSQL..."
          sleep 2
        done
      env:
        PGPASSWORD: "Pokemon"

    - name: Sync Test Database
      run: docker-compose exec app yarn sync:test

    - name: Run Tests
      run: docker-compose exec app yarn test --verbose

    - name: Stop Docker Containers
      if: always()
      run: docker-compose down --volumes --remove-orphans
