name: Integración Continua

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/-1', 'lts/*', 'current']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Install Dependencies
      run: cd backend && yarn install

    - name: Run Tests in Docker
      run: cd backend && yarn docker:test

    - name: Cleanup Docker Containers
      if: always()
      run: cd backend && yarn docker:stop
