name: Integración Continua

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/-1', 'lts/*', 'current']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    - name: Install Dependencies
      run: cd backend && yarn install

    - name: Start Docker Services
      run: cd backend && yarn docker:start

    - name: Wait for PostgreSQL to be Ready
      run: |
        cd backend
        until docker-compose exec db pg_isready -U pokemon_admin -d pokemon_trading_test; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done

    - name: Sync Database
      run: cd backend && docker-compose exec app yarn sync:db

    - name: Run Tests
      run: cd backend && yarn docker:test

    - name: Cleanup Docker Containers
      if: always()
      run: cd backend && yarn docker:stop
