name: Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/cardtrading:latest .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/cardtrading:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/cardtrading:$(date +'%Y%m%d%H%M%S')

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/cardtrading:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/cardtrading:$(date +'%Y%m%d%H%M%S')
